export { default as PropertyCard } from './PropertyCard' 
export { default as OnImgBtn } from './OnImgBtn' 
export { default as CityCard } from './CityCard' 
export { default as FeaturedProperties } from './FeaturedProperties' 
export { default as TestimonialSlider } from './TestimonialSlider' 
export { default as VideoBanner } from './VideoBanner' 
export { default as PurchaseCard } from './PurchaseCards' 